SRCS = $(wildcard *.c)
OBJECTS = $(SRCS:.c=.o)
#OBJECTS = $(patsubst %.c, %.o, $(SRCS))
TARGET = prog.out
CC = gcc
CFLAGS = -Wall -W

$(TARGET) : $(OBJECTS)
	$(CC) $(CFLAGS) -o $@ $^

clean :
	rm $(OBJECTS)
	rm $(TARGET)

